In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import pandas_profiling

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import train_test_split

from sklearn.feature_selection import RFE, SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from statsmodels.stats.outliers_influence import variance_inflation_factor 

import statsmodels.formula.api as smf
from sklearn import metrics
import scipy.stats as stats

from sklearn.neighbors import KNeighborsClassifier

In [2]:
Data = pd.read_csv("Test.txt",delimiter=",",header=None)

In [3]:
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)
pd.set_option("display.width",1000)
Data

0     1         2     3      4     5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21   22  23   24    25   26   27    28    29    30   31   32    33    34    35    36    37   38    39    40       41  42
0       0   tcp   private   REJ      0     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  229  10  0.0  0.00  1.0  1.0  0.04  0.06  0.00  255   10  0.04  0.06  0.00  0.00  0.00  0.0  1.00  1.00  neptune  21
1       0   tcp   private   REJ      0     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  136   1  0.0  0.00  1.0  1.0  0.01  0.06  0.00  255    1  0.00  0.06  0.00  0.00  0.00  0.0  1.00  1.00  neptune  21
2       2   tcp  ftp_data    SF  12983     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    1   1  0.0  0.00  0.0  0.0  1.00  0.00  0.00  134   86  0.61  0.04  0.61  0.02  0.00  0.0  0.00  0.00   normal  21
3       0  icmp     eco_i    SF     20     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    1  65  0.0  0.00  0.0  0.0  1.00  0.00  1.00    3   57  1.00  0.00  1.00  0.28  0.00  0.0  0.00  0.00    saint  15
4       1   tcp    telnet  RSTO      0    15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    1   8  0.0  0.12  1.0  0.5  1.00  0.00  0.75   29   86  0.31  0.17  0.03  0.02  0.00  0.0  0.83  0.71    mscan  11
...    ..   ...       ...   ...    ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ...   ...  ...  ...   ...   ...   ...  ...  ...   ...   ...   ...   ...   ...  ...   ...   ...      ...  ..
22539   0   tcp      smtp    SF    794   333   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0    1   1  0.0  0.00  0.0  0.0  1.00  0.00  0.00  100  141  0.72  0.06  0.01  0.01  0.01  0.0  0.00  0.00   normal  21
22540   0   tcp      http    SF    317   938   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0    2  11  0.0  0.00  0.0  0.0  1.00  0.00  0.18  197  255  1.00  0.00  0.01  0.01  0.01  0.0  0.00  0.00   normal  21
22541   0   tcp      http    SF  54540  8314   0   0   0   2   0   1   1   0   0   0   0   0   0   0   0   0    5  10  0.0  0.00  0.0  0.0  1.00  0.00  0.20  255  255  1.00  0.00  0.00  0.00  0.00  0.0  0.07  0.07     back  15
22542   0   udp  domain_u    SF     42    42   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    4   6  0.0  0.00  0.0  0.0  1.00  0.00  0.33  255  252  0.99  0.01  0.00  0.00  0.00  0.0  0.00  0.00   normal  21
22543   0   tcp    sunrpc   REJ      0     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0    4  10  0.0  0.00  1.0  1.0  0.25  1.00  1.00  255   21  0.08  0.03  0.00  0.00  0.00  0.0  0.44  1.00    mscan  14

[22544 rows x 43 columns]

In [4]:
col_name = ["Duration","Protocol_type","Service","Flag","Src_bytes", "Dst_bytes","Land", "Wrong_fragment","Urgent","Hot","Num_failed_logins","Logged_in","Num_compromised","Root_shell","Su_attempted","Num_root","Num_file_creations","Num_shells","Num_access_files","Num_outbound_cmds","Is_host_login","Is_guest_login","Count","Srv_count","Serror_rate","Srv_serror_rate",
"Rerror_rate","Srv_rerror_rate","Same_srv_rate","Diff_srv_rate","Srv_diff_host_rate","Dst_host_count","Dst_host_srv_count","Dst_host_same_srv_rate","Dst_host_diff_srv_rate","Dst_host_same_src_port_rate",
"Dst_host_srv_diff_host_rate","Dst_host_serror_rate","Dst_host_srv_serror_rate", "Dst_host_rerror_rate","Dst_host_srv_rerror_rate","Attack", "Last_flag"]

In [5]:
for i in range (0,43):
    Data = Data.rename(columns={i:col_name[i]})

In [6]:
#Data.to_excel("Data.xlsx")

In [7]:
Data['Activity'] = np.where(Data.Attack=="normal",0,1)

In [8]:
print(Data.Activity.value_counts()) # 0 is normal and 1 is attack which is our event

1    12833
0     9711
Name: Activity, dtype: int64


In [9]:
Data.Service = pd.Series(np.where((Data.Service=="http"),"http",(np.where((Data.Service=="private"),"private",(
                np.where((Data.Service=="domain_u"),"domain_u",(np.where((Data.Service=="smtp"),"smtp",(
                                                                      np.where((Data.Service=="ftp_data"),"ftp_data","other_type"))))))))))

In [10]:
Data.Service.value_counts()

http          7853
other_type    7238
private       4774
smtp           934
domain_u       894
ftp_data       851
Name: Service, dtype: int64

In [11]:
print(Data.shape)

(22544, 44)


In [12]:
y_multi = Data.Attack

In [13]:
Data = Data.drop(columns="Attack",axis=1)

In [14]:
Data.head(1)

Duration Protocol_type  Service Flag  Src_bytes  Dst_bytes  Land  Wrong_fragment  Urgent  Hot  Num_failed_logins  Logged_in  Num_compromised  Root_shell  Su_attempted  Num_root  Num_file_creations  Num_shells  Num_access_files  Num_outbound_cmds  Is_host_login  Is_guest_login  Count  Srv_count  Serror_rate  Srv_serror_rate  Rerror_rate  Srv_rerror_rate  Same_srv_rate  Diff_srv_rate  Srv_diff_host_rate  Dst_host_count  Dst_host_srv_count  Dst_host_same_srv_rate  Dst_host_diff_srv_rate  Dst_host_same_src_port_rate  Dst_host_srv_diff_host_rate  Dst_host_serror_rate  Dst_host_srv_serror_rate  Dst_host_rerror_rate  Dst_host_srv_rerror_rate  Last_flag  Activity
0         0           tcp  private  REJ          0          0     0               0       0    0                  0          0                0           0             0         0                   0           0                 0                  0              0               0    229         10          0.0              0.0          1.0              1.0           0.04           0.06                 0.0             255                  10                    0.04                    0.06                          0.0                          0.0                   0.0                       0.0                   1.0                       1.0         21         1

In [15]:
#Profile = pandas_profiling.ProfileReport(Data)
#Profile.to_file("Output.html")

##### On basis of Pandas Profiling dropping variable which are highly corelated  and which are constant

In [16]:
Data = Data.drop(columns={"Num_root","Srv_serror_rate","Srv_rerror_rate","Dst_host_serror_rate","Dst_host_srv_serror_rate","Dst_host_rerror_rate","Dst_host_srv_rerror_rate"})
Data = Data.drop(columns={"Wrong_fragment"})

In [17]:
Data=Data.drop(columns={"Num_access_files","Num_failed_logins","Num_file_creations","Num_outbound_cmds","Num_shells"},axis=1)

In [18]:
Data_num = Data.loc[:,Data.columns.difference(["Protocol_type","Service","Flag","Urgent","Land","Logged_in","Root_shell","Su_attempted","Is_host_login","Is_guest_login"])]

In [19]:
def var_summary(x):
    return pd.Series([x.count(), x.isnull().sum(), x.sum(), x.mean(), x.median(),  x.std(), x.var(), x.std()/x.mean(), x.min(), x.dropna().quantile(0.01), x.dropna().quantile(0.05),x.dropna().quantile(0.10),x.dropna().quantile(0.25),x.dropna().quantile(0.50),x.dropna().quantile(0.75), x.dropna().quantile(0.90),x.dropna().quantile(0.95), x.dropna().quantile(0.99),x.max()], 
                  index=['N', 'NMISS', 'SUM', 'MEAN','MEDIAN', 'STD', 'VAR', 'CV','MIN', 'P1' , 'P5' ,'P10' ,'P25' ,'P50' ,'P75' ,'P90' ,'P95' ,'P99' ,'MAX'])
Data_num.apply(lambda x: var_summary(x)).T

N  NMISS           SUM          MEAN  MEDIAN            STD           VAR         CV  MIN   P1    P5    P10     P25     P50     P75      P90       P95          P99         MAX
Activity                     22544.0    0.0  1.283300e+04      0.569242    1.00       0.495193  2.452164e-01   0.869916  0.0  0.0  0.00   0.00    0.00    1.00    1.00     1.00      1.00       1.0000         1.0
Count                        22544.0    0.0  1.781615e+06     79.028345    8.00     128.539248  1.652234e+04   1.626496  0.0  1.0  1.00   1.00    1.00    8.00  123.25   256.00    400.85     511.0000       511.0
Diff_srv_rate                22544.0    0.0  2.120800e+03      0.094074    0.00       0.259138  6.715231e-02   2.754620  0.0  0.0  0.00   0.00    0.00    0.00    0.06     0.09      1.00       1.0000         1.0
Dst_bytes                    22544.0    0.0  4.635089e+07   2056.018808   46.00   21219.297609  4.502586e+08  10.320576  0.0  0.0  0.00   0.00    0.00   46.00  601.00  4099.10   8314.00   26032.0400   1345927.0
Dst_host_count               22544.0    0.0  4.370592e+06    193.869411  255.00      94.035663  8.842706e+03   0.485046  0.0  1.0  6.00  20.00  121.00  255.00  255.00   255.00    255.00     255.0000       255.0
Dst_host_diff_srv_rate       22544.0    0.0  2.041130e+03      0.090540    0.01       0.220717  4.871593e-02   2.437787  0.0  0.0  0.00   0.00    0.00    0.01    0.06     0.15      0.75       1.0000         1.0
Dst_host_same_src_port_rate  22544.0    0.0  2.981690e+03      0.132261    0.00       0.306268  9.380025e-02   2.315637  0.0  0.0  0.00   0.00    0.00    0.00    0.03     0.85      1.00       1.0000         1.0
Dst_host_same_srv_rate       22544.0    0.0  1.372302e+04      0.608722    0.92       0.435688  1.898242e-01   0.715743  0.0  0.0  0.00   0.02    0.07    0.92    1.00     1.00      1.00       1.0000         1.0
Dst_host_srv_count           22544.0    0.0  3.173080e+06    140.750532  168.00     111.783972  1.249566e+04   0.794199  0.0  1.0  1.00   3.00   15.00  168.00  255.00   255.00    255.00     255.0000       255.0
Dst_host_srv_diff_host_rate  22544.0    0.0  4.427300e+02      0.019638    0.00       0.085394  7.292115e-03   4.348293  0.0  0.0  0.00   0.00    0.00    0.00    0.01     0.04      0.06       0.4057         1.0
Duration                     22544.0    0.0  4.933959e+06    218.859076    0.00    1407.176612  1.980146e+06   6.429601  0.0  0.0  0.00   0.00    0.00    0.00    0.00     4.00    283.00    7589.5700     57715.0
Hot                          22544.0    0.0  2.376000e+03      0.105394    0.00       0.928428  8.619786e-01   8.809125  0.0  0.0  0.00   0.00    0.00    0.00    0.00     0.00      0.00       2.0000       101.0
Last_flag                    22544.0    0.0  4.061970e+05     18.017965   20.00       4.270361  1.823598e+01   0.237006  0.0  2.0  9.00  12.00   17.00   20.00   21.00    21.00     21.00      21.0000        21.0
Num_compromised              22544.0    0.0  2.703000e+03      0.119899    0.00       7.269597  5.284704e+01  60.631077  0.0  0.0  0.00   0.00    0.00    0.00    0.00     0.00      0.00       1.0000       796.0
Rerror_rate                  22544.0    0.0  5.375910e+03      0.238463    0.00       0.416118  1.731539e-01   1.744999  0.0  0.0  0.00   0.00    0.00    0.00    0.25     1.00      1.00       1.0000         1.0
Same_srv_rate                22544.0    0.0  1.669033e+04      0.740345    1.00       0.412496  1.701530e-01   0.557168  0.0  0.0  0.01   0.03    0.25    1.00    1.00     1.00      1.00       1.0000         1.0
Serror_rate                  22544.0    0.0  2.320310e+03      0.102924    0.00       0.295367  8.724158e-02   2.869768  0.0  0.0  0.00   0.00    0.00    0.00    0.00     0.50      1.00       1.0000         1.0
Src_bytes                    22544.0    0.0  2.343550e+08  10395.450231   54.00  472786.431088  2.235270e+11  45.480130  0.0  0.0  0.00   0.00    0.00   54.00  287.00  1032.00  15876.00  283618.0000  62825648.0
Srv_count                 

In [20]:
def missing(x):
    x = x.fillna(x.mean())
    return x

In [21]:
Data_num= Data_num.apply(missing)

In [22]:
def outliers(x):
    lc = x.quantile(0.01)
    uc = x.quantile(0.99)
    return x.clip(lower = lc, upper = uc)

In [23]:
Data_num = Data_num.apply(outliers)

In [24]:
Data_cat = Data.loc[:,["Protocol_type","Service","Flag","Urgent","Land","Logged_in","Root_shell","Su_attempted","Is_host_login","Is_guest_login","Activity"]]

In [25]:
def missing_cat(x):
    x=x.fillna(x.mode)
    return x

In [26]:
Data_cat = Data_cat.apply(missing_cat)

In [27]:
def create_dummies(df, colname):
    col_dummy = pd.get_dummies(df[colname],prefix=colname,drop_first=True)
    df = pd.concat([df,col_dummy],axis=1)
    df.drop(colname,axis=1,inplace=True)
    return df

In [28]:
for c_feature in Data_cat.columns[0:len(Data_cat.columns)-1]:
    Data_cat[c_feature] = Data_cat[c_feature].astype('category')
    Data_cat = create_dummies(Data_cat,c_feature)

In [29]:
Data_cat.head(2)

Activity  Protocol_type_tcp  Protocol_type_udp  Service_ftp_data  Service_http  Service_other_type  Service_private  Service_smtp  Flag_REJ  Flag_RSTO  Flag_RSTOS0  Flag_RSTR  Flag_S0  Flag_S1  Flag_S2  Flag_S3  Flag_SF  Flag_SH  Urgent_1  Urgent_2  Urgent_3  Land_1  Logged_in_1  Root_shell_1  Su_attempted_1  Su_attempted_2  Is_host_login_1  Is_guest_login_1
0         1                  1                  0                 0             0                   0                1             0         1          0            0          0        0        0        0        0        0        0         0         0         0       0            0             0               0               0                0                 0
1         1                  1                  0                 0             0                   0                1             0         1          0            0          0        0        0        0        0        0        0         0         0         0       0            0             0               0               0                0                 0

In [30]:
Pre_processing_data = pd.concat([Data_num,Data_cat],axis=1)

In [31]:
Normal_Data = Pre_processing_data

In [32]:
Normal_Data = Normal_Data.drop(columns="Activity",axis =1 )

In [33]:
Normal_Data['Activity'] = Data.Activity

In [34]:
Normal_Num = Normal_Data.iloc[:,range(0,19)]
Normal_Num['Activity'] = Normal_Data.Activity

In [35]:
Normal_Num.head(3)

Count  Diff_srv_rate  Dst_bytes  Dst_host_count  Dst_host_diff_srv_rate  Dst_host_same_src_port_rate  Dst_host_same_srv_rate  Dst_host_srv_count  Dst_host_srv_diff_host_rate  Duration  Hot  Last_flag  Num_compromised  Rerror_rate  Same_srv_rate  Serror_rate  Src_bytes  Srv_count  Srv_diff_host_rate  Activity
0    229           0.06        0.0             255                    0.06                         0.00                    0.04                  10                         0.00       0.0    0         21                0          1.0           0.04          0.0          0         10                 0.0         1
1    136           0.06        0.0             255                    0.06                         0.00                    0.00                   1                         0.00       0.0    0         21                0          1.0           0.01          0.0          0          1                 0.0         1
2      1           0.00        0.0             134                    0.04                         0.61                    0.61                  86                         0.02       2.0    0         21                0          0.0           1.00          0.0      12983          1                 0.0         0

In [36]:
Normal_Num.shape

(22544, 20)

In [37]:
Normal_cat = Normal_Data.iloc[:,range(19,47)]

In [38]:
Normal_cat.shape

(22544, 28)

In [42]:
Variable_for_vif = Normal_Data.loc[:,['Count','Diff_srv_rate','Dst_bytes','Dst_host_count','Dst_host_diff_srv_rate','Dst_host_same_srv_rate','Dst_host_srv_count','Flag_S0','Flag_SF','Last_flag','Logged_in_1','Protocol_type_tcp','Protocol_type_udp','Same_srv_rate','Serror_rate','Service_http','Service_other_type','Service_private','Src_bytes','Flag_REJ']]

In [45]:
X = Variable_for_vif 
  
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 
  
print(vif_data)

                   feature       VIF
0                    Count  2.183662
1            Diff_srv_rate  2.185327
2                Dst_bytes  1.415405
3   Dst_host_diff_srv_rate  1.975920
4        Protocol_type_udp  2.036584
5            Same_srv_rate  6.082844
6              Serror_rate  1.487135
7             Service_http  4.280224
8       Service_other_type  3.598961
9          Service_private  2.827195
10               Src_bytes  1.103057
11                Flag_REJ  2.350912


#### Variables to drop with high VIF are 

`Dst_host_count,Dst_host_same_srv_rate,Dst_host_srv_count,Flag_S0,Flag_SF,Last_flag,Logged_in_1,Protocol_type_tcp`

In [44]:
Variable_for_vif = Variable_for_vif.drop(columns={"Dst_host_count","Dst_host_same_srv_rate","Dst_host_count","Dst_host_same_srv_rate","Dst_host_srv_count","Flag_S0","Flag_SF","Last_flag","Logged_in_1","Protocol_type_tcp"},axis =1)

In [46]:
"+".join(Variable_for_vif)

'Count+Diff_srv_rate+Dst_bytes+Dst_host_diff_srv_rate+Protocol_type_udp+Same_srv_rate+Serror_rate+Service_http+Service_other_type+Service_private+Src_bytes+Flag_REJ'

In [49]:
Variable_for_vif['Activity'] = Normal_Data.Activity

In [50]:
train, test = train_test_split(Normal_Data,test_size = 0.3,random_state = 123)

In [51]:
model = smf.logit(formula='Activity~Count+Diff_srv_rate+Dst_bytes+Dst_host_diff_srv_rate+Protocol_type_udp+Same_srv_rate+Serror_rate+Service_other_type+Service_private+Src_bytes+Flag_REJ',data=Normal_Data).fit()

Optimization terminated successfully.
         Current function value: 0.210223
         Iterations 10


In [52]:
print(model.summary())

                           Logit Regression Results                           
Dep. Variable:               Activity   No. Observations:                22544
Model:                          Logit   Df Residuals:                    22532
Method:                           MLE   Df Model:                           11
Date:                Sun, 29 Nov 2020   Pseudo R-squ.:                  0.6924
Time:                        01:55:00   Log-Likelihood:                -4739.3
converged:                       True   LL-Null:                       -15409.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -0.4306      0.226     -1.902      0.057      -0.874       0.013
Count                     -0.0029      0.000    -13.288      0.000      -0.003      -0.003
Diff

`Y = -2.565905+5.642172*Count-2.858759*Diff_srv_rate-4.707721*Dst_bytes+1.700660*Dst_host_diff_srv_rate-4.429371*Protocol_type_udp-1.353055*Same_srv_rate+4.627557*Serror_rate+4.237987*Service_other_type+8.617284*Service_private+5.266135*Src_bytes+0.895385*Flag_REJ`

In [53]:
train['prob'] = model.predict(train)
test['prob'] = model.predict(test)

In [54]:
train_auc = metrics.roc_auc_score(train.Activity,train.prob)
train_auc = pd.Series(train_auc)
train_auc

0    0.978204
dtype: float64

In [55]:
test_auc = metrics.roc_auc_score(test.Activity,test.prob)
test_auc=pd.Series(test_auc)
test_auc

0    0.976191
dtype: float64

In [56]:
Gini_train = 2*train_auc-1
Gini_train=pd.Series(Gini_train)
print(Gini_train)
Gini_test = 2*test_auc-1
Gini_test=pd.Series(Gini_test)
print(Gini_test)

0    0.956409
dtype: float64
0    0.952381
dtype: float64


In [57]:
temp = train
roc_df = pd.DataFrame()
for cutoff in np.linspace(0,1):
    temp['Activity_predicted'] = np.where(train.prob>cutoff,1,0)
    temp['TN'] = np.where(((train.Activity==0)&(train.Activity_predicted==0)),1,0)
    temp['TP'] = np.where(((train.Activity==1)&(train.Activity_predicted==1)),1,0)
    temp['FP'] = np.where(((train.Activity==0)&(train.Activity_predicted==1)),1,0)
    temp['FN'] = np.where(((train.Activity==1)&(train.Activity_predicted==0)),1,0)
    senstivity = temp.TP.sum()/(temp.TP.sum()+temp.FN.sum())
    specitivity = temp.TN.sum()/(temp.TN.sum()+temp.FP.sum())
    accuracy = (temp.TP.sum()+temp.TN.sum())/(temp.Activity_predicted.count())
    temp_df = pd.DataFrame([cutoff,senstivity,specitivity,accuracy]).T
    temp_df.columns = ["cutoff","senstivity","specitivity","accuracy"]
    roc_df = pd.concat([roc_df,temp_df])

In [58]:
roc_df['Total'] = roc_df['senstivity'] + roc_df['specitivity']

In [59]:
roc_df.sort_values(by =['Total'],ascending=False).head(1)

cutoff  senstivity  specitivity  accuracy     Total
0  0.469388    0.949439     0.922595  0.937769  1.872034

In [60]:
roc_df[roc_df.Total==roc_df.Total.max()]

cutoff  senstivity  specitivity  accuracy     Total
0  0.469388    0.949439     0.922595  0.937769  1.872034

In [61]:
train['Activity_Predicted'] = np.where(train.prob > 0.469388,1,0)
test['Activity_Predicted']=np.where(test.prob > 0.469388,1,0)

In [62]:
Logit_Confusion_train = metrics.confusion_matrix(train.Activity,train.Activity_Predicted)
Logit_Confusion_train

array([[6329,  531],
       [ 451, 8469]])

In [63]:
Logit_Confusion_test = metrics.confusion_matrix(test.Activity,test.Activity_Predicted)
Logit_Confusion_test

array([[2640,  211],
       [ 208, 3705]])

In [64]:
train_classificaton = metrics.classification_report(train.Activity,train.Activity_Predicted)
print(train_classificaton)

              precision    recall  f1-score   support

           0       0.93      0.92      0.93      6860
           1       0.94      0.95      0.95      8920

    accuracy                           0.94     15780
   macro avg       0.94      0.94      0.94     15780
weighted avg       0.94      0.94      0.94     15780



In [65]:
test_classificaton = metrics.classification_report(test.Activity,test.Activity_Predicted)
print(test_classificaton)

              precision    recall  f1-score   support

           0       0.93      0.93      0.93      2851
           1       0.95      0.95      0.95      3913

    accuracy                           0.94      6764
   macro avg       0.94      0.94      0.94      6764
weighted avg       0.94      0.94      0.94      6764



In [66]:
Logit = pd.concat([train_auc,test_auc,Gini_train,Gini_test],axis =1)
Logit.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
Logit

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.978204    0.976191    0.956409   0.952381

In [67]:
train['decile'] = pd.qcut(train['prob'],10,labels =False)
test['decile'] = pd.qcut(test['prob'],10,labels = False)

In [68]:
train['normal'] = 1-train.Activity
test['normal'] = 1-test.Activity

In [69]:
decile_train = train.groupby(by=['decile']).agg(min_prob = ('prob','min'),
                                                max_prob = ('prob','max'),
                                                no_of_attack=('Activity','sum'),
                                               no_of_normal = ('normal','sum'),
                                               total = ('Activity','count'))

In [70]:
decile_test = test.groupby(by=['decile']).agg(min_prob = ('prob','min'),
                                             max_prob = ('prob','max'),
                                             no_of_attack = ('Activity','sum'),
                                             no_of_normal = ('normal','sum'),
                                             total = ('Activity','count'))

In [71]:
compare_train = train.loc[:,["Activity",'Activity_Predicted',"decile",'prob']]
compare_test = test.loc[:,["Activity",'Activity_Predicted',"decile",'prob']]

In [72]:
compare_train.head(10)

Activity  Activity_Predicted  decile      prob
19352         1                   0       3  0.127108
2436          1                   1       5  0.938085
5799          1                   1       4  0.780313
16090         1                   1       6  0.943461
18005         1                   1       6  0.943669
13433         0                   0       3  0.106814
22483         1                   1       9  0.999901
4141          1                   1       7  0.979537
21825         0                   0       0  0.027188
4334          1                   1       4  0.474723

In [73]:
Variable_for_vif = Variable_for_vif.drop(columns="Service_http",axis =1)

In [74]:
target = Variable_for_vif.Activity
features = Variable_for_vif.loc[:,Variable_for_vif.columns.difference(['Activity'])]

In [75]:
train_X,test_x,train_Y,test_y = train_test_split(features,target, test_size=0.3, random_state=123)

In [76]:
train_X.columns

Index(['Count', 'Diff_srv_rate', 'Dst_bytes', 'Dst_host_diff_srv_rate', 'Flag_REJ', 'Protocol_type_udp', 'Same_srv_rate', 'Serror_rate', 'Service_other_type', 'Service_private', 'Src_bytes'], dtype='object')

In [77]:
print(train_X.shape)
print(train_Y.shape)
print(test_x.shape)
print(test_y.shape)

(15780, 11)
(15780,)
(6764, 11)
(6764,)


In [78]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [79]:
sc = StandardScaler()

In [80]:
Knn_data = sc.fit_transform(features)
Knn_data = pd.DataFrame(Knn_data)
Knn_data.columns = features.columns

In [81]:
train_X1, test_X1 , train_Y1, test_Y1 = train_test_split(Knn_data,target,test_size = 0.3,random_state = 344) 

In [138]:
param_grid_knn = {'n_neighbors':[300,400,500,600,700,800,900,1000],
              'weights': ['distance']}
knn_model = GridSearchCV(KNeighborsClassifier(), param_grid = param_grid_knn, cv=2, scoring = 'f1_weighted',verbose = True)
knn_model = knn_model.fit(train_X1,train_Y1)

Fitting 2 folds for each of 8 candidates, totalling 16 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:  6.9min finished


In [139]:
knn_model.best_params_

{'n_neighbors': 300, 'weights': 'distance'}

In [82]:
knn_model = KNeighborsClassifier(n_neighbors=300,weights = "distance", n_jobs=-1).fit(train_X1,train_Y1)

In [83]:
pred_y = knn_model.predict(train_X1)

In [84]:
print(metrics.classification_report(train_Y1, pred_y))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      6815
           1       1.00      1.00      1.00      8965

    accuracy                           1.00     15780
   macro avg       1.00      1.00      1.00     15780
weighted avg       1.00      1.00      1.00     15780



In [85]:
Knn_Confusion_train = metrics.confusion_matrix(train_Y1,pred_y)
Knn_Confusion_train

array([[6776,   39],
       [  33, 8932]])

In [87]:
Knn_Auroc_Score_train = metrics.roc_auc_score(train_Y1,pred_y)
Knn_Auroc_Score_train = pd.Series(Knn_Auroc_Score_train)
print(Knn_Auroc_Score_train)
Knn_Gini_train = 2*Knn_Auroc_Score_train -1
Knn_Gini_train = pd.Series(Knn_Gini_train)
print(Knn_Gini_train)

0    0.995298
dtype: float64
0    0.990596
dtype: float64


In [88]:
Knn_Accuracy_train = metrics.accuracy_score(train_Y1,pred_y)
Knn_Accuracy_train = pd.Series(Knn_Accuracy_train)
Knn_Accuracy_train

0    0.995437
dtype: float64

In [89]:
knn_model_test = KNeighborsClassifier(n_neighbors=300,weights = "distance",n_jobs=-1).fit(test_X1,test_Y1)

In [90]:
pred_y1 = knn_model_test.predict(test_X1)

In [91]:
print(metrics.classification_report(test_Y1,pred_y1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2896
           1       1.00      1.00      1.00      3868

    accuracy                           1.00      6764
   macro avg       1.00      1.00      1.00      6764
weighted avg       1.00      1.00      1.00      6764



In [92]:
Knn_Confusion_test = metrics.confusion_matrix(test_Y1,pred_y1)
Knn_Confusion_test

array([[2886,   10],
       [  13, 3855]])

In [93]:
Knn_Auroc_Score_test = metrics.roc_auc_score(test_Y1,pred_y1)
Knn_Auroc_Score_test = pd.Series(Knn_Auroc_Score_test)
print(Knn_Auroc_Score_test)
Knn_Gini_test = 2*Knn_Auroc_Score_test -1
Knn_Gini_test = pd.Series(Knn_Gini_test)
print(Knn_Gini_test)

0    0.996593
dtype: float64
0    0.993186
dtype: float64


In [94]:
Knn_Accuracy_test = metrics.accuracy_score(test_Y1,pred_y1)
Knn_Accuracy_test = pd.Series(Knn_Accuracy_test)
Knn_Accuracy_test

0    0.9966
dtype: float64

In [95]:
Knn = pd.concat([Knn_Auroc_Score_train,Knn_Auroc_Score_test,Knn_Gini_train,Knn_Gini_test],axis=1)
Knn.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
Knn

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.995298    0.996593    0.990596   0.993186

In [96]:
from sklearn.tree import DecisionTreeClassifier

In [153]:
param_grid_dt = {'max_depth': np.arange(3, 5),
             'max_features': np.arange(3,5)}
dt_model = GridSearchCV(DecisionTreeClassifier(),param_grid = param_grid_dt,cv =2 , scoring = 'f1_weighted')
dt_model = dt_model.fit(train_X,train_y)

In [154]:
dt_model.best_params_

{'max_depth': 3, 'max_features': 4}

In [97]:
dt_model_train = DecisionTreeClassifier(max_depth = 3,max_features = 4).fit(train_X,train_Y)

In [98]:
print(metrics.classification_report(train_Y,dt_model_train.predict(train_X)))

              precision    recall  f1-score   support

           0       0.90      0.93      0.91      6860
           1       0.94      0.92      0.93      8920

    accuracy                           0.92     15780
   macro avg       0.92      0.92      0.92     15780
weighted avg       0.92      0.92      0.92     15780



In [99]:
Dt_Auroc_Score_train = metrics.roc_auc_score(train_Y,dt_model_train.predict(train_X))
Dt_Auroc_Score_train = pd.Series(Dt_Auroc_Score_train)
print(Dt_Auroc_Score_train)
Dt_Gini_train = 2*Dt_Auroc_Score_train - 1
Dt_Gini_train = pd.Series(Dt_Gini_train)
print(Dt_Gini_train)

0    0.922946
dtype: float64
0    0.845892
dtype: float64


In [100]:
DT_Confusion_train=metrics.confusion_matrix(train_Y,dt_model_train.predict(train_X))
DT_Confusion_train

array([[6355,  505],
       [ 718, 8202]])

In [101]:
print("Accuracy",metrics.accuracy_score(train_Y,dt_model_train.predict(train_X)))

Accuracy 0.9224968314321926


In [102]:
dt_model_test = DecisionTreeClassifier(max_depth = 4, max_features = 4).fit(test_x,test_y)

In [103]:
print(metrics.classification_report(test_y,dt_model_test.predict(test_x)))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91      2851
           1       0.93      0.94      0.94      3913

    accuracy                           0.92      6764
   macro avg       0.92      0.92      0.92      6764
weighted avg       0.92      0.92      0.92      6764



In [104]:
DT_Confusion_test = metrics.confusion_matrix(test_y,dt_model_test.predict(test_x))
DT_Confusion_test

array([[2584,  267],
       [ 243, 3670]])

In [105]:
Dt_Auroc_Score_test = metrics.roc_auc_score(test_y,dt_model_test.predict(test_x))
Dt_Auroc_Score_test = pd.Series(Dt_Auroc_Score_test)
print(Dt_Auroc_Score_test)
Dt_Gini_test = 2*Dt_Auroc_Score_test -1 
Dt_Gini_test = pd.Series(Dt_Gini_test)
print(Dt_Gini_test)

0    0.922124
dtype: float64
0    0.844248
dtype: float64


In [106]:
print("Accuracy",metrics.accuracy_score(test_y,dt_model_test.predict(test_x)))

Accuracy 0.9246008279124778


In [107]:
DT = pd.concat([Dt_Auroc_Score_train,Dt_Auroc_Score_test,Dt_Gini_train,Dt_Gini_test],axis = 1)
DT.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
DT

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.922946    0.922124    0.845892   0.844248

In [108]:
from sklearn.ensemble import BaggingClassifier

In [133]:
param_bagging = {"n_estimators":[700,800,900,1000,1100,1200]}
model_bagging = GridSearchCV(BaggingClassifier(),param_grid = param_bagging,cv = 2,verbose = True, n_jobs =-1)
model_bagging = model_bagging.fit(train_X,train_Y)

Fitting 2 folds for each of 6 candidates, totalling 12 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:  6.9min finished


In [134]:
model_bagging.best_params_

{'n_estimators': 1200}

In [109]:
bagging_model_train = BaggingClassifier(n_estimators = 1200).fit(train_X,train_Y)

In [110]:
predict_bagging = bagging_model_train.predict(train_X)

In [111]:
print(metrics.classification_report(train_Y,predict_bagging))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      6860
           1       1.00      1.00      1.00      8920

    accuracy                           1.00     15780
   macro avg       1.00      1.00      1.00     15780
weighted avg       1.00      1.00      1.00     15780



In [112]:
Bagging_Confusion_train = metrics.confusion_matrix(train_Y,predict_bagging)
Bagging_Confusion_train

array([[6821,   39],
       [  31, 8889]])

In [113]:
Bagging_Auroc_train =  metrics.roc_auc_score(train_Y,predict_bagging)
Bagging_Auroc_train = pd.Series(Bagging_Auroc_train)
print(Bagging_Auroc_train)
Bagging_Gini_train = 2*Bagging_Auroc_train-1
Bagging_Gini_train = pd.Series(Bagging_Gini_train)
print(Bagging_Gini_train)

0    0.99542
dtype: float64
0    0.99084
dtype: float64


In [114]:
print("Accuracy",metrics.accuracy_score(train_Y,predict_bagging))

Accuracy 0.9955640050697085


In [115]:
bagging_model_test = BaggingClassifier(n_estimators = 1200).fit(test_x,test_y)

In [116]:
bagging_predict_test = bagging_model_test.predict(test_x)

In [117]:
print(metrics.classification_report(test_y,bagging_predict_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2851
           1       1.00      1.00      1.00      3913

    accuracy                           1.00      6764
   macro avg       1.00      1.00      1.00      6764
weighted avg       1.00      1.00      1.00      6764



In [118]:
Bagging_Confusion_test = metrics.confusion_matrix(test_y,bagging_predict_test)
Bagging_Confusion_test

array([[2838,   13],
       [   9, 3904]])

In [119]:
Bagging_Auroc_test = metrics.roc_auc_score(test_y,bagging_predict_test)
Bagging_Auroc_test = pd.Series(Bagging_Auroc_test)
print(Bagging_Auroc_test)
Bagging_Gini_test = 2*Bagging_Auroc_test -1 
Bagging_Gini_test = pd.Series(Bagging_Gini_test)
print(Bagging_Gini_test)

0    0.99657
dtype: float64
0    0.99314
dtype: float64


In [120]:
Bagging = pd.concat([Bagging_Auroc_train,Bagging_Auroc_test,Bagging_Gini_train,Bagging_Gini_test],axis =1)
Bagging.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
Bagging

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0      0.99542     0.99657     0.99084    0.99314

In [121]:
from sklearn.ensemble import RandomForestClassifier

In [145]:
param_rf = {'n_estimators':[100,200,300,400,500,600],"max_depth":[3,4,5,6],"max_features" :[6,7,8,9]}
model_rf = GridSearchCV(RandomForestClassifier(),param_grid = param_rf, verbose = True,n_jobs = -1)
modelrf = model_rf.fit(train_X,train_Y)

Fitting 5 folds for each of 96 candidates, totalling 480 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed: 23.2min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed: 67.7min
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed: 76.9min finished


In [146]:
modelrf.best_params_

{'max_depth': 6, 'max_features': 7, 'n_estimators': 300}

In [122]:
model_rf_train = RandomForestClassifier(n_estimators=300, max_depth = 6, max_features = 7).fit(train_X,train_Y)
rf_predict_train = model_rf_train.predict(train_X)

In [123]:
print(metrics.classification_report(train_Y,rf_predict_train))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98      6860
           1       0.98      0.99      0.98      8920

    accuracy                           0.98     15780
   macro avg       0.98      0.98      0.98     15780
weighted avg       0.98      0.98      0.98     15780



In [124]:
RF_Confusion_train = metrics.confusion_matrix(train_Y,rf_predict_train)
RF_Confusion_train

array([[6657,  203],
       [ 113, 8807]])

In [125]:
RF_Auroc_train = metrics.roc_auc_score(train_Y,rf_predict_train)
RF_Auroc_train = pd.Series(RF_Auroc_train)
print(RF_Auroc_train)
RF_Gini_train = 2*RF_Auroc_train - 1
RF_Gini_train = pd.Series(RF_Gini_train)
print(RF_Gini_train)

0    0.97887
dtype: float64
0    0.95774
dtype: float64


In [126]:
print("Accuracy",metrics.accuracy_score(train_Y,rf_predict_train))

Accuracy 0.9799746514575411


In [127]:
model_rf_test = RandomForestClassifier(n_estimators=300, max_depth = 6, max_features = 7).fit(test_x,test_y)

In [128]:
rf_predict_test = model_rf_test.predict(test_x)

In [129]:
print(metrics.classification_report(test_y,rf_predict_test))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      2851
           1       0.97      1.00      0.98      3913

    accuracy                           0.98      6764
   macro avg       0.98      0.98      0.98      6764
weighted avg       0.98      0.98      0.98      6764



In [130]:
RF_Confusion_test = metrics.confusion_matrix(test_y,rf_predict_test)
RF_Confusion_test

array([[2748,  103],
       [  18, 3895]])

In [131]:
RF_Auroc_test = metrics.roc_auc_score(test_y,rf_predict_test)
RF_Auroc_test = pd.Series(RF_Auroc_test)
print(RF_Auroc_test)
RF_Gini_test = 2*RF_Auroc_test -1 
RF_Gini_test = pd.Series(RF_Gini_test)
print(RF_Gini_test)

0    0.979636
dtype: float64
0    0.959272
dtype: float64


In [132]:
print("Accuracy",metrics.accuracy_score(test_y,rf_predict_test))

Accuracy 0.9821111768184506


In [133]:
RF = pd.concat([RF_Auroc_train,RF_Auroc_test,RF_Gini_train,RF_Gini_test],axis =1)
RF.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
RF

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0      0.97887    0.979636     0.95774   0.959272

## Boosting

In [134]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [138]:
param_ada = {"n_estimators":[100,200,400,600,800],
            "learning_rate":[10 ** x for x in range(-3,3)]}

In [158]:
gridsearch_ada = GridSearchCV(GradientBoostingClassifier(),param_grid = param_ada,n_jobs = -1,cv = 2, verbose = True)
model_ada = gridsearch_ada.fit(train_X,train_Y)

Fitting 2 folds for each of 30 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  5.8min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:  8.2min finished


In [159]:
model_ada.best_params_

{'learning_rate': 0.1, 'n_estimators': 800}

In [135]:
ada_train = AdaBoostClassifier(n_estimators = 800 , learning_rate = 0.1).fit(train_X,train_Y)

In [136]:
ada_train_predict = ada_train.predict(train_X)

In [137]:
print(metrics.classification_report(train_Y,ada_train_predict))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94      6860
           1       0.95      0.96      0.96      8920

    accuracy                           0.95     15780
   macro avg       0.95      0.95      0.95     15780
weighted avg       0.95      0.95      0.95     15780



In [138]:
Ada_confusion_train = metrics.confusion_matrix(train_Y,ada_train_predict)
Ada_confusion_train

array([[6424,  436],
       [ 331, 8589]])

In [139]:
Ada_Auroc_train = metrics.roc_auc_score(train_Y,ada_train_predict)
Ada_Auroc_train = pd.Series(Ada_Auroc_train)
print(Ada_Auroc_train)
Ada_Gini_train = 2*Ada_Auroc_train -1 
Ada_Gini_train = pd.Series(Ada_Gini_train)
print(Ada_Gini_train)

0    0.949668
dtype: float64
0    0.899336
dtype: float64


In [140]:
print("Accuracy",metrics.accuracy_score(train_Y,ada_train_predict))

Accuracy 0.9513941698352345


In [141]:
ada_test = AdaBoostClassifier(n_estimators = 800 , learning_rate = 0.1).fit(test_x,test_y)
ada_test_predict = ada_test.predict(test_x)
print(metrics.classification_report(test_y,ada_test_predict))

              precision    recall  f1-score   support

           0       0.95      0.94      0.95      2851
           1       0.96      0.96      0.96      3913

    accuracy                           0.95      6764
   macro avg       0.95      0.95      0.95      6764
weighted avg       0.95      0.95      0.95      6764



In [142]:
Ada_confusion_test = metrics.confusion_matrix(test_y,ada_test_predict)
Ada_confusion_test

array([[2680,  171],
       [ 139, 3774]])

In [143]:
Ada_Aurco_test = metrics.roc_auc_score(test_y,ada_test_predict)
Ada_Aurco_test = pd.Series(Ada_Aurco_test)
print(Ada_Aurco_test)
Ada_Gini_test = 2*Ada_Aurco_test -1 
Ada_Gini_test = pd.Series(Ada_Gini_test)
print(Ada_Gini_test)

0    0.952249
dtype: float64
0    0.904498
dtype: float64


In [144]:
print("Accuracy Score",metrics.accuracy_score(test_y,ada_test_predict))

Accuracy Score 0.9541691306918982


In [145]:
ADA = pd.concat([Ada_Auroc_train,Ada_Aurco_test,Ada_Gini_train,Ada_Gini_test],axis=1)
ADA.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
ADA

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.949668    0.952249    0.899336   0.904498

In [167]:
model_gbm = GridSearchCV(GradientBoostingClassifier(),param_grid = param_ada,cv = 2, verbose = True, n_jobs =-1)
model_train = model_gbm.fit(train_X,train_Y)

Fitting 2 folds for each of 30 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:  7.6min finished


In [168]:
model_train.best_params_

{'learning_rate': 0.1, 'n_estimators': 800}

In [146]:
model_gbm = GradientBoostingClassifier(n_estimators = 800, learning_rate = 0.1).fit(train_X,train_Y)

In [147]:
gbms_predict = model_gbm.predict(train_X)

In [148]:
print(metrics.classification_report(train_Y,gbms_predict))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6860
           1       0.99      0.99      0.99      8920

    accuracy                           0.99     15780
   macro avg       0.99      0.99      0.99     15780
weighted avg       0.99      0.99      0.99     15780



In [149]:
Gbm_confusion_train = metrics.confusion_matrix(train_Y,gbms_predict)
Gbm_confusion_train

array([[6808,   52],
       [  53, 8867]])

In [150]:
Gbm_Auroc_train = metrics.roc_auc_score(train_Y,gbms_predict)
Gbm_Auroc_train = pd.Series(Gbm_Auroc_train)
print(Gbm_Auroc_train)
Gbm_Gini_train = 2*Gbm_Auroc_train - 1
Gbm_Gini_train = pd.Series(Gbm_Gini_train)
print(Gbm_Gini_train)

0    0.993239
dtype: float64
0    0.986478
dtype: float64


In [151]:
print("Accuracy_Score",metrics.accuracy_score(train_Y,gbms_predict))

Accuracy_Score 0.9933460076045627


In [152]:
model_gbm_test = GradientBoostingClassifier(n_estimators = 800, learning_rate = 0.1).fit(test_x,test_y)
gbms_predict_test = model_gbm_test.predict(test_x)
print(metrics.classification_report(test_y,gbms_predict_test))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      2851
           1       1.00      1.00      1.00      3913

    accuracy                           1.00      6764
   macro avg       1.00      1.00      1.00      6764
weighted avg       1.00      1.00      1.00      6764



In [153]:
Gbm_confusion_test = metrics.confusion_matrix(test_y,gbms_predict_test)
Gbm_confusion_test

array([[2836,   15],
       [  11, 3902]])

In [154]:
Gbm_Auroc_test = metrics.roc_auc_score(test_y,gbms_predict_test)
Gbm_Auroc_test = pd.Series(Gbm_Auroc_test)
print(Gbm_Auroc_test)
Gbm_Gini_test = 2*Gbm_Auroc_test -1
Gbm_Gini_test = pd.Series(Gbm_Gini_test)
print(Gbm_Gini_test)

0    0.995964
dtype: float64
0    0.991928
dtype: float64


In [155]:
print("Accuracy_Score",metrics.accuracy_score(test_y,gbms_predict_test))

Accuracy_Score 0.9961561206386753


In [156]:
GBM = pd.concat([Gbm_Auroc_train,Gbm_Auroc_test,Gbm_Gini_train,Gbm_Gini_test],axis=1)
GBM.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
GBM

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.993239    0.995964    0.986478   0.991928

In [157]:
from xgboost import XGBClassifier

In [158]:
xgb_estimator = XGBClassifier( learning_rate=0.01,
                               n_estimators=1000,
                               max_depth=5,
                               min_child_weight=1,
                               gamma=1,
                               subsample=0.8,
                               colsample_bytree=0.8,
                               n_jobs=-1,
                               reg_alpa=1,
                               scale_pos_weight=1,
                               random_state=42,
                               verbose=1)

In [159]:
xgb_model = xgb_estimator.fit(train_X,train_Y)

[01:58:27] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { reg_alpa, verbose } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




In [160]:
xgb_predict = xgb_model.predict(train_X)

In [161]:
print(metrics.classification_report(train_Y,xgb_predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      6860
           1       0.99      0.99      0.99      8920

    accuracy                           0.99     15780
   macro avg       0.99      0.99      0.99     15780
weighted avg       0.99      0.99      0.99     15780



In [162]:
Xgb_confusion_train = metrics.confusion_matrix(train_Y,xgb_predict)
Xgb_confusion_train

array([[6737,  123],
       [  84, 8836]])

In [163]:
XGB_Auroc_train = metrics.roc_auc_score(train_Y,xgb_predict)
XGB_Auroc_train = pd.Series(XGB_Auroc_train)
print(XGB_Auroc_train)
XGB_Gini_train = 2*XGB_Auroc_train - 1
XGB_Gini_train = pd.Series(XGB_Gini_train)
print(XGB_Gini_train)

0    0.986326
dtype: float64
0    0.972653
dtype: float64


In [164]:
print("Accuracy",metrics.accuracy_score(train_Y,xgb_predict))

Accuracy 0.9868821292775666


In [165]:
xgb_model_test = xgb_estimator.fit(test_x,test_y)

[01:58:42] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { reg_alpa, verbose } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




In [166]:
xgb_test_predict = xgb_model_test.predict(test_x)

In [167]:
print(metrics.classification_report(test_y,xgb_test_predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      2851
           1       0.99      0.99      0.99      3913

    accuracy                           0.99      6764
   macro avg       0.99      0.99      0.99      6764
weighted avg       0.99      0.99      0.99      6764



In [168]:
Xgb_confusion_test = metrics.confusion_matrix(test_y,xgb_test_predict)
Xgb_confusion_test

array([[2803,   48],
       [  24, 3889]])

In [169]:
XGB_Auroc_test = metrics.roc_auc_score(test_y,xgb_test_predict)
XGB_Auroc_test = pd.Series(XGB_Auroc_test)
print(XGB_Auroc_test)
XGB_Gini_test = 2*XGB_Auroc_test - 1
XGB_Gini_test = pd.Series(XGB_Gini_test)
print(XGB_Gini_test)

0    0.988515
dtype: float64
0    0.97703
dtype: float64


In [170]:
XGB = pd.concat([XGB_Auroc_train,XGB_Auroc_test,XGB_Gini_train,XGB_Gini_test],axis = 1)
XGB.columns = ["Auroc_Train","Auroc_Test","Gini_Train","Gini_Test"]
XGB

Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.986326    0.988515    0.972653    0.97703

In [171]:
print("Logistic Regression","\n",Logit)
print("KNN","\n",Knn)
print("DT","\n",DT)
print("Bagging","\n",Bagging)
print("RF","\n",RF)
print("ADA","\n",ADA)
print("GBM","\n",GBM)
print("XGB","\n",XGB)

Logistic Regression 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.978204    0.976191    0.956409   0.952381
KNN 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.995298    0.996593    0.990596   0.993186
DT 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.922946    0.922124    0.845892   0.844248
Bagging 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0      0.99542     0.99657     0.99084    0.99314
RF 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0      0.97887    0.979636     0.95774   0.959272
ADA 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.949668    0.952249    0.899336   0.904498
GBM 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.993239    0.995964    0.986478   0.991928
XGB 
    Auroc_Train  Auroc_Test  Gini_Train  Gini_Test
0     0.986326    0.988515    0.972653    0.97703


In [172]:
print("Logistic_Train","\n", Logit_Confusion_train)
print("KNN_Train","\n",Knn_Confusion_train)
print("DT)Train","\n",DT_Confusion_train)
print("Baggin_Train","\n",Bagging_Confusion_train)
print("RF_Train","\n",RF_Confusion_train)
print("ADA_Train","\n",Ada_confusion_train)
print("GBM_Train","\n",Gbm_confusion_train)
print("XGB_Train","\n",Xgb_confusion_train)

print("Logistic_Test","\n", Logit_Confusion_test)
print("KNN_Test","\n",Knn_Confusion_test)
print("DT_Test","\n",DT_Confusion_test)
print("Bagging_Test","\n",Bagging_Confusion_test)
print("RF_Test","\n",RF_Confusion_test)
print("ADA_Test","\n",Ada_confusion_test)
print("GBM_Test","\n",Gbm_confusion_test)
print("XGB_Test","\n",Xgb_confusion_test)

Logistic_Train 
 [[6329  531]
 [ 451 8469]]
KNN_Train 
 [[6776   39]
 [  33 8932]]
DT)Train 
 [[6355  505]
 [ 718 8202]]
Baggin_Train 
 [[6821   39]
 [  31 8889]]
RF_Train 
 [[6657  203]
 [ 113 8807]]
ADA_Train 
 [[6424  436]
 [ 331 8589]]
GBM_Train 
 [[6808   52]
 [  53 8867]]
XGB_Train 
 [[6737  123]
 [  84 8836]]
Logistic_Test 
 [[2640  211]
 [ 208 3705]]
KNN_Test 
 [[2886   10]
 [  13 3855]]
DT_Test 
 [[2584  267]
 [ 243 3670]]
Bagging_Test 
 [[2838   13]
 [   9 3904]]
RF_Test 
 [[2748  103]
 [  18 3895]]
ADA_Test 
 [[2680  171]
 [ 139 3774]]
GBM_Test 
 [[2836   15]
 [  11 3902]]
XGB_Test 
 [[2803   48]
 [  24 3889]]


### From the above matrices, Bagging turns out to be giving the best results.

In [173]:
import os

In [ ]:
from sklearn.svm import LinearSVC, LinearSVR, SVC, SVR

In [ ]:
model_svm = SVC(kernel='rbf', class_weight='balanced')


In [ ]:
param_grid = {'C': [1, 5, 10, 50],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(model_svm, param_grid, verbose = True)

grid.fit(train_X, train_y)

# Multinominal Classification

In [174]:
Variable_for_vif

Count  Diff_srv_rate  Dst_bytes  Dst_host_diff_srv_rate  Protocol_type_udp  Same_srv_rate  Serror_rate  Service_other_type  Service_private  Src_bytes  Flag_REJ  Activity
0        229           0.06        0.0                    0.06                  0           0.04          0.0                   0                1          0         1         1
1        136           0.06        0.0                    0.06                  0           0.01          0.0                   0                1          0         1         1
2          1           0.00        0.0                    0.04                  0           1.00          0.0                   0                0      12983         0         0
3          1           0.00        0.0                    0.00                  0           1.00          0.0                   1                0         20         0         1
4          1           0.00       15.0                    0.17                  0           1.00          0.0                   1                0          0         0         1
...      ...            ...        ...                     ...                ...            ...          ...                 ...              ...        ...       ...       ...
22539      1           0.00      333.0                    0.06                  0           1.00          0.0                   0                0        794         0         0
22540      2           0.00      938.0                    0.00                  0           1.00          0.0                   0                0        317         0         0
22541      5           0.00     8314.0                    0.00                  0           1.00          0.0                   0                0      54540         0         1
22542      4           0.00       42.0                    0.01                  1           1.00          0.0                   0                0         42         0         0
22543      4           1.00        0.0                    0.03                  0           0.25          0.0                   1                0          0         1         1

[22544 rows x 12 columns]

In [175]:
Variable_for_vif['Attack'] = y_multi

In [176]:
Variable_for_vif.Attack.value_counts()

normal             9711
neptune            4657
guess_passwd       1231
mscan               996
warezmaster         944
apache2             737
satan               735
processtable        685
smurf               665
back                359
snmpguess           331
saint               319
mailbomb            293
snmpgetattack       178
portsweep           157
ipsweep             141
httptunnel          133
nmap                 73
pod                  41
buffer_overflow      20
multihop             18
named                17
ps                   15
sendmail             14
rootkit              13
xterm                13
teardrop             12
xlock                 9
land                  7
xsnoop                4
ftp_write             3
loadmodule            2
worm                  2
sqlattack             2
udpstorm              2
perl                  2
phf                   2
imap                  1
Name: Attack, dtype: int64

In [177]:
Variable_for_vif=Variable_for_vif.drop('Activity',axis =1)

In [178]:
Variable_for_vif['Attack_class'] = np.where(Variable_for_vif.Attack == 'normal','Normal',
(np.where((Variable_for_vif.Attack=="back")|(Variable_for_vif.Attack=="land")|(Variable_for_vif.Attack=="neptune")|(Variable_for_vif.Attack=="pod")|(Variable_for_vif.Attack=="smurf")|(Variable_for_vif.Attack=="teardrop")|(Variable_for_vif.Attack=="apache2")|(Variable_for_vif.Attack=="udpstorm")|(Variable_for_vif.Attack=="processtable")|(Variable_for_vif.Attack=="worm"),"DoS",
(np.where((Variable_for_vif.Attack=="satan")|(Variable_for_vif.Attack=="ipsweep")|(Variable_for_vif.Attack=="portsweep")|(Variable_for_vif.Attack=="mscan")|(Variable_for_vif.Attack=="saint")|(Variable_for_vif.Attack=="nmap"),"Probe",
(np.where((Variable_for_vif.Attack=="guess_passwd")|(Variable_for_vif.Attack=="ftp_write")|(Variable_for_vif.Attack=="imap")|(Variable_for_vif.Attack=="phf")|(Variable_for_vif.Attack=="multihop")|(Variable_for_vif.Attack=="warezmaster")|(Variable_for_vif.Attack=="warezclient")|(Variable_for_vif.Attack=="spy")|(Variable_for_vif.Attack=="xlock")|(Variable_for_vif.Attack=="xsnoop")|(Variable_for_vif.Attack=="snmpguess")|(Variable_for_vif.Attack=="snmpgetattack")|(Variable_for_vif.Attack=="httptunnel")|(Variable_for_vif.Attack=="sendmail")|(Variable_for_vif.Attack=="named"),"R2L",
(np.where((Variable_for_vif.Attack=="buffer_overflow")|(Variable_for_vif.Attack=="loadmodule")|(Variable_for_vif.Attack=="rootkit")|(Variable_for_vif.Attack=="perl")|(Variable_for_vif.Attack=="sqlattack")|(Variable_for_vif.Attack=="xterm")|(Variable_for_vif.Attack=="ps"),"U2R","Missclassification")))))))))

In [179]:
Variable_for_vif.Attack_class.value_counts()

Normal                9711
DoS                   7167
R2L                   2885
Probe                 2421
Missclassification     293
U2R                     67
Name: Attack_class, dtype: int64

In [180]:
Variable_for_vif=Variable_for_vif.drop('Attack',axis=1)

In [181]:
Variable_for_vif

Count  Diff_srv_rate  Dst_bytes  Dst_host_diff_srv_rate  Protocol_type_udp  Same_srv_rate  Serror_rate  Service_other_type  Service_private  Src_bytes  Flag_REJ Attack_class
0        229           0.06        0.0                    0.06                  0           0.04          0.0                   0                1          0         1          DoS
1        136           0.06        0.0                    0.06                  0           0.01          0.0                   0                1          0         1          DoS
2          1           0.00        0.0                    0.04                  0           1.00          0.0                   0                0      12983         0       Normal
3          1           0.00        0.0                    0.00                  0           1.00          0.0                   1                0         20         0        Probe
4          1           0.00       15.0                    0.17                  0           1.00          0.0                   1                0          0         0        Probe
...      ...            ...        ...                     ...                ...            ...          ...                 ...              ...        ...       ...          ...
22539      1           0.00      333.0                    0.06                  0           1.00          0.0                   0                0        794         0       Normal
22540      2           0.00      938.0                    0.00                  0           1.00          0.0                   0                0        317         0       Normal
22541      5           0.00     8314.0                    0.00                  0           1.00          0.0                   0                0      54540         0          DoS
22542      4           0.00       42.0                    0.01                  1           1.00          0.0                   0                0         42         0       Normal
22543      4           1.00        0.0                    0.03                  0           0.25          0.0                   1                0          0         1        Probe

[22544 rows x 12 columns]

In [182]:
X = Variable_for_vif.drop('Attack_class',axis = 1)
Y = Variable_for_vif.Attack_class

In [183]:
train_X, test_x, train_Y, test_y =  train_test_split(X,Y, test_size = 0.3,random_state = 252)

In [184]:
sc1 = StandardScaler()
Knn_data = sc1.fit_transform(X)
Knn_data = pd.DataFrame(Knn_data)
Knn_data.columns = X.columns

In [185]:
train_knn_X, test_knn_X, train_knn_y, test_knn_y =  train_test_split(Knn_data,Y, test_size = 0.3,random_state = 252)

In [202]:
param_grid_knn = {"n_neighbors":[300,400,500,600,700,800,900,1000],
                 "weights":['distance']}
model_knn = GridSearchCV(KNeighborsClassifier(),param_grid = param_grid_knn, cv = 2, scoring = 'f1_weighted',verbose = True, n_jobs=-1)
model_knn = model_knn.fit(train_knn_X,train_knn_y)

Fitting 2 folds for each of 8 candidates, totalling 16 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 out of  16 | elapsed:  4.7min finished


In [204]:
model_knn.best_params_

{'n_neighbors': 300, 'weights': 'distance'}

In [186]:
model_knn = KNeighborsClassifier(n_neighbors = 300,weights="distance").fit(train_knn_X,train_knn_y)

In [187]:
knn_predict_multi = model_knn.predict(train_knn_X)

In [188]:
accuracy_knn = metrics.accuracy_score(train_knn_y,knn_predict_multi)
print(accuracy_knn)

0.990874524714829


In [189]:
knn_cm = metrics.classification_report(train_knn_y,knn_predict_multi)
print(knn_cm)

                    precision    recall  f1-score   support

               DoS       0.99      1.00      1.00      4999
Missclassification       1.00      1.00      1.00       201
            Normal       1.00      0.99      0.99      6796
             Probe       0.98      0.98      0.98      1687
               R2L       0.98      0.97      0.98      2053
               U2R       1.00      1.00      1.00        44

          accuracy                           0.99     15780
         macro avg       0.99      0.99      0.99     15780
      weighted avg       0.99      0.99      0.99     15780



In [190]:
KNN_MULTI_CM_Train = metrics.confusion_matrix(train_knn_y,knn_predict_multi)
KNN_MULTI_CM_Train

array([[4987,    0,    0,   12,    0,    0],
       [   0,  201,    0,    0,    0,    0],
       [   1,    0, 6757,    0,   38,    0],
       [  29,    0,    0, 1646,   12,    0],
       [   0,    0,   33,   19, 2001,    0],
       [   0,    0,    0,    0,    0,   44]])

In [194]:
model_knn_test = KNeighborsClassifier(n_neighbors = 300,weights="distance").fit(test_knn_X,test_knn_y)

In [195]:
knn_pred = model_knn_test.predict(test_knn_X)

In [196]:
print(metrics.classification_report(test_knn_y,knn_pred))

                    precision    recall  f1-score   support

               DoS       1.00      1.00      1.00      2168
Missclassification       1.00      1.00      1.00        92
            Normal       1.00      1.00      1.00      2915
             Probe       0.99      0.98      0.98       734
               R2L       0.98      0.98      0.98       832
               U2R       1.00      1.00      1.00        23

          accuracy                           0.99      6764
         macro avg       0.99      0.99      0.99      6764
      weighted avg       0.99      0.99      0.99      6764



In [197]:
KNN_MULTI_CM_Test = metrics.confusion_matrix(test_knn_y,knn_pred)
KNN_MULTI_CM_Test

array([[2167,    0,    0,    1,    0,    0],
       [   0,   92,    0,    0,    0,    0],
       [   0,    0, 2905,    0,   10,    0],
       [  10,    0,    0,  719,    5,    0],
       [   0,    0,    9,    6,  817,    0],
       [   0,    0,    0,    0,    0,   23]])

In [198]:
from sklearn.tree import DecisionTreeClassifier

In [181]:
param_grid_dt = {'max_depth': [3,4,5,6], 'max_leaf_nodes': [5,6,7,8,9,10]}
model_dt = GridSearchCV(DecisionTreeClassifier(),param_grid= param_grid_dt,cv = 2, scoring = 'f1_weighted',verbose = True, n_jobs=-1)
model_dt = model_dt.fit(train_X,train_Y)

Fitting 2 folds for each of 24 candidates, totalling 48 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  48 out of  48 | elapsed:   21.2s finished


In [182]:
model_dt.best_params_

{'max_depth': 4, 'max_leaf_nodes': 10}

In [199]:
model_dt = DecisionTreeClassifier(max_depth = 4, max_leaf_nodes = 10).fit(train_X,train_Y)

In [200]:
dt_prediction = model_dt.predict(train_X)

In [201]:
dt_cm = metrics.classification_report(train_Y,dt_prediction)
print(dt_cm)

                    precision    recall  f1-score   support

               DoS       0.98      0.96      0.97      4999
Missclassification       0.75      1.00      0.86       201
            Normal       0.97      0.89      0.93      6796
             Probe       0.86      0.64      0.73      1687
               R2L       0.60      0.92      0.73      2053
               U2R       0.00      0.00      0.00        44

          accuracy                           0.89     15780
         macro avg       0.69      0.74      0.70     15780
      weighted avg       0.91      0.89      0.89     15780



In [202]:
DT_MULTI_CM_Train = metrics.confusion_matrix(train_Y,dt_prediction)
DT_MULTI_CM_Train

array([[4819,    0,    7,   19,  154,    0],
       [   0,  201,    0,    0,    0,    0],
       [  67,   63, 6054,  132,  480,    0],
       [  13,    0,   13, 1075,  586,    0],
       [   5,    5,  134,   19, 1890,    0],
       [   0,    0,    3,    0,   41,    0]])

In [203]:
dt_test = DecisionTreeClassifier(max_depth = 4, max_leaf_nodes = 10).fit(test_x,test_y)

In [204]:
dt_test_prediction = dt_test.predict(test_x)

In [205]:
print(metrics.classification_report(test_y,dt_test_prediction))

                    precision    recall  f1-score   support

               DoS       0.99      0.96      0.98      2168
Missclassification       0.73      1.00      0.84        92
            Normal       0.97      0.88      0.92      2915
             Probe       0.88      0.69      0.77       734
               R2L       0.57      0.90      0.70       832
               U2R       0.00      0.00      0.00        23

          accuracy                           0.89      6764
         macro avg       0.69      0.74      0.70      6764
      weighted avg       0.91      0.89      0.89      6764



In [206]:
DT_MULTI_CM_Test = metrics.confusion_matrix(test_y,dt_test_prediction)
DT_MULTI_CM_Test

array([[2092,    0,    4,    1,   71,    0],
       [   0,   92,    0,    0,    0,    0],
       [  23,   33, 2562,   57,  240,    0],
       [   4,    0,    2,  504,  224,    0],
       [   1,    1,   67,   11,  752,    0],
       [   0,    0,    2,    0,   21,    0]])

baging

In [207]:
from sklearn.ensemble import BaggingClassifier

In [223]:
param_bagging = {"n_estimators":[300,400,500,600,700,800,900,1000,1100,1200]}
model_bagging = GridSearchCV(BaggingClassifier(),param_grid = param_bagging,cv = 2,verbose = True, n_jobs =-1)
model_bagging = model_bagging.fit(train_X,train_Y)

Fitting 2 folds for each of 10 candidates, totalling 20 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:  9.7min finished


In [224]:
model_bagging.best_params_

{'n_estimators': 1000}

In [208]:
bagging_model_train = BaggingClassifier(n_estimators = 1000).fit(train_X,train_Y)

predict_bagging = bagging_model_train.predict(train_X)

print(metrics.classification_report(train_Y,predict_bagging))

                    precision    recall  f1-score   support

               DoS       0.99      1.00      1.00      4999
Missclassification       1.00      1.00      1.00       201
            Normal       1.00      0.99      0.99      6796
             Probe       0.98      0.98      0.98      1687
               R2L       0.97      0.98      0.98      2053
               U2R       1.00      1.00      1.00        44

          accuracy                           0.99     15780
         macro avg       0.99      0.99      0.99     15780
      weighted avg       0.99      0.99      0.99     15780



In [209]:
Bagging_MULTI_CM_Train = metrics.confusion_matrix(train_Y,predict_bagging)
Bagging_MULTI_CM_Train

array([[4986,    0,    0,   13,    0,    0],
       [   0,  201,    0,    0,    0,    0],
       [   1,    0, 6746,    0,   49,    0],
       [  28,    0,    0, 1647,   12,    0],
       [   0,    0,   22,   19, 2012,    0],
       [   0,    0,    0,    0,    0,   44]])

In [210]:
bagging_model_test = BaggingClassifier(n_estimators = 1000).fit(test_x,test_y)

bagging_predict_test = bagging_model_test.predict(test_x)

print(metrics.classification_report(test_y,bagging_predict_test))

                    precision    recall  f1-score   support

               DoS       1.00      1.00      1.00      2168
Missclassification       1.00      1.00      1.00        92
            Normal       1.00      1.00      1.00      2915
             Probe       0.99      0.98      0.98       734
               R2L       0.98      0.99      0.98       832
               U2R       1.00      1.00      1.00        23

          accuracy                           0.99      6764
         macro avg       0.99      0.99      0.99      6764
      weighted avg       0.99      0.99      0.99      6764



In [211]:
Bagging_MULTI_CM_Test = metrics.confusion_matrix(test_y,bagging_predict_test)
Bagging_MULTI_CM_Test

array([[2167,    0,    0,    1,    0,    0],
       [   0,   92,    0,    0,    0,    0],
       [   0,    0, 2903,    0,   12,    0],
       [  10,    0,    0,  717,    7,    0],
       [   0,    0,    7,    4,  821,    0],
       [   0,    0,    0,    0,    0,   23]])

In [212]:
from sklearn.ensemble import RandomForestClassifier

In [227]:
param_rf = {'n_estimators':[100,200,300,400,500,600],"max_depth":[3,4,5,6],"max_features" :[6,7,8,9]}
model_rf = GridSearchCV(RandomForestClassifier(),param_grid = param_rf, verbose = True,n_jobs = -1)
modelrf = model_rf.fit(train_X,train_Y)

Fitting 5 folds for each of 96 candidates, totalling 480 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed: 23.5min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed: 67.1min
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed: 76.0min finished


In [228]:
modelrf.best_params_

{'max_depth': 6, 'max_features': 6, 'n_estimators': 200}

In [213]:
model_rf_train = RandomForestClassifier(n_estimators=200, max_depth = 6, max_features = 6).fit(train_X,train_Y)
rf_predict_train = model_rf_train.predict(train_X)

print(metrics.classification_report(train_Y,rf_predict_train))

                    precision    recall  f1-score   support

               DoS       0.98      0.99      0.99      4999
Missclassification       1.00      1.00      1.00       201
            Normal       0.97      0.98      0.97      6796
             Probe       0.91      0.95      0.93      1687
               R2L       0.95      0.87      0.91      2053
               U2R       1.00      0.07      0.13        44

          accuracy                           0.96     15780
         macro avg       0.97      0.81      0.82     15780
      weighted avg       0.96      0.96      0.96     15780



In [214]:
RF_MULTI_CM_Train = metrics.confusion_matrix(train_Y,rf_predict_train)
RF_MULTI_CM_Train

array([[4959,    0,   12,   20,    8,    0],
       [   0,  201,    0,    0,    0,    0],
       [  33,    0, 6629,   59,   75,    0],
       [  66,    0,   15, 1606,    0,    0],
       [   0,    0,  174,   89, 1790,    0],
       [   0,    0,   32,    0,    9,    3]])

In [215]:
model_rf_test = RandomForestClassifier(n_estimators=500, max_depth = 6, max_features = 6).fit(test_x,test_y)

rf_predict_test = model_rf_test.predict(test_x)

print(metrics.classification_report(test_y,rf_predict_test))

                    precision    recall  f1-score   support

               DoS       0.99      0.99      0.99      2168
Missclassification       1.00      1.00      1.00        92
            Normal       0.97      0.98      0.98      2915
             Probe       0.92      0.96      0.94       734
               R2L       0.95      0.90      0.92       832
               U2R       0.85      0.48      0.61        23

          accuracy                           0.97      6764
         macro avg       0.95      0.88      0.91      6764
      weighted avg       0.97      0.97      0.97      6764



In [216]:
RF_MULTI_CM_Test = metrics.confusion_matrix(test_y,rf_predict_test)
RF_MULTI_CM_Test

array([[2147,    0,   18,    3,    0,    0],
       [   0,   92,    0,    0,    0,    0],
       [   7,    0, 2851,   23,   33,    1],
       [  23,    0,    5,  705,    1,    0],
       [   0,    0,   53,   32,  746,    1],
       [   0,    0,    6,    0,    6,   11]])

In [217]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [231]:
param_ada = {"n_estimators":[100,200,400,600,800],
            "learning_rate":[10 ** x for x in range(-3,3)]}

gridsearch_ada = GridSearchCV(GradientBoostingClassifier(),param_grid = param_ada,n_jobs = -1,cv = 2, verbose = True)
model_ada = gridsearch_ada.fit(train_X,train_Y)

Fitting 2 folds for each of 30 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed: 35.1min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed: 50.7min finished


In [232]:
model_ada.best_params_

{'learning_rate': 0.1, 'n_estimators': 100}

In [218]:
ada_train = AdaBoostClassifier(n_estimators = 100 , learning_rate = 0.1).fit(train_X,train_Y)

ada_train_predict = ada_train.predict(train_X)

print(metrics.classification_report(train_Y,ada_train_predict))

                    precision    recall  f1-score   support

               DoS       0.00      0.00      0.00      4999
Missclassification       1.00      1.00      1.00       201
            Normal       0.58      0.98      0.73      6796
             Probe       0.00      0.00      0.00      1687
               R2L       0.24      0.47      0.32      2053
               U2R       0.00      0.00      0.00        44

          accuracy                           0.50     15780
         macro avg       0.30      0.41      0.34     15780
      weighted avg       0.29      0.50      0.37     15780



In [219]:
ADA_MULTI_CM_Train = metrics.confusion_matrix(train_Y,ada_train_predict)
ADA_MULTI_CM_Train

array([[   0,    0, 3394,    0, 1605,    0],
       [   0,  201,    0,    0,    0,    0],
       [  14,    0, 6655,    0,  127,    0],
       [   0,    0,  377,    0, 1310,    0],
       [   0,    0, 1088,    0,  965,    0],
       [   0,    0,   43,    0,    1,    0]])

In [220]:
ada_test = AdaBoostClassifier(n_estimators = 100 , learning_rate = 0.1).fit(test_x,test_y)

ada_test_predict = ada_test.predict(test_x)

print(metrics.classification_report(test_y,ada_test_predict))

                    precision    recall  f1-score   support

               DoS       0.95      0.68      0.79      2168
Missclassification       1.00      0.99      0.99        92
            Normal       0.72      0.96      0.82      2915
             Probe       0.99      0.26      0.41       734
               R2L       0.36      0.46      0.40       832
               U2R       0.00      0.00      0.00        23

          accuracy                           0.73      6764
         macro avg       0.67      0.56      0.57      6764
      weighted avg       0.78      0.73      0.72      6764



In [221]:
ADA_MULTI_CM_Test = metrics.confusion_matrix(test_y,ada_test_predict)
ADA_MULTI_CM_Test

array([[1466,    0,  497,    0,  205,    0],
       [   0,   91,    1,    0,    0,    0],
       [  33,    0, 2805,    2,   75,    0],
       [  34,    0,  118,  192,  390,    0],
       [   5,    0,  446,    0,  381,    0],
       [   0,    0,   22,    0,    1,    0]])

In [235]:
model_gbm = GridSearchCV(GradientBoostingClassifier(),param_grid = param_ada,cv = 2, verbose = True, n_jobs =-1)
model_train = model_gbm.fit(train_X,train_Y)

Fitting 2 folds for each of 30 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed: 35.1min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed: 51.3min finished


In [236]:
model_train.best_params_

{'learning_rate': 0.1, 'n_estimators': 100}

In [222]:
model_gbm = GradientBoostingClassifier(n_estimators = 100, learning_rate = 0.1).fit(train_X,train_Y)

gbms_predict = model_gbm.predict(train_X)

print(metrics.classification_report(train_Y,gbms_predict))

                    precision    recall  f1-score   support

               DoS       0.99      0.99      0.99      4999
Missclassification       1.00      1.00      1.00       201
            Normal       0.98      0.98      0.98      6796
             Probe       0.95      0.96      0.96      1687
               R2L       0.96      0.95      0.95      2053
               U2R       0.97      0.86      0.92        44

          accuracy                           0.98     15780
         macro avg       0.98      0.96      0.97     15780
      weighted avg       0.98      0.98      0.98     15780



In [223]:
GBM_Multi_CM_train = metrics.confusion_matrix(train_Y,gbms_predict)
GBM_Multi_CM_train

array([[4961,    0,   15,   22,    1,    0],
       [   0,  201,    0,    0,    0,    0],
       [   9,    0, 6684,   25,   78,    0],
       [  39,    0,   13, 1627,    8,    0],
       [   2,    0,   73,   30, 1947,    1],
       [   0,    0,    4,    0,    2,   38]])

In [224]:
model_gbm_test = GradientBoostingClassifier(n_estimators = 100, learning_rate = 0.1).fit(test_x,test_y)

gbms_predict_test = model_gbm_test.predict(test_x)

print(metrics.classification_report(test_y,gbms_predict_test))

                    precision    recall  f1-score   support

               DoS       0.99      1.00      0.99      2168
Missclassification       1.00      1.00      1.00        92
            Normal       0.99      0.99      0.99      2915
             Probe       0.97      0.97      0.97       734
               R2L       0.97      0.96      0.96       832
               U2R       1.00      0.96      0.98        23

          accuracy                           0.99      6764
         macro avg       0.99      0.98      0.98      6764
      weighted avg       0.99      0.99      0.99      6764



In [225]:
GBM_Multi_CM_test = metrics.confusion_matrix(test_y,gbms_predict_test)
GBM_Multi_CM_test

array([[2159,    0,    5,    2,    2,    0],
       [   0,   92,    0,    0,    0,    0],
       [   0,    0, 2886,    8,   21,    0],
       [  15,    0,    3,  711,    5,    0],
       [   0,    0,   21,   11,  800,    0],
       [   0,    0,    1,    0,    0,   22]])

In [226]:
from xgboost import XGBClassifier

xgb_estimator = XGBClassifier( learning_rate=0.01,
                               n_estimators=1000,
                               max_depth=5,
                               min_child_weight=1,
                               gamma=1,
                               subsample=0.8,
                               colsample_bytree=0.8,
                               n_jobs=-1,
                               reg_alpa=1,
                               scale_pos_weight=1,
                               random_state=42,
                               verbose=1)

xgb_model = xgb_estimator.fit(train_X,train_Y)

xgb_predict = xgb_model.predict(train_X)

print(metrics.classification_report(train_Y,xgb_predict))


[02:00:51] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { reg_alpa, scale_pos_weight, verbose } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


                    precision    recall  f1-score   support

               DoS       0.99      0.99      0.99      4999
Missclassification       1.00      1.00      1.00       201
            Normal       0.99      0.98      0.99      6796
             Probe       0.95      0.97      0.96      1687
               R2L       0.96      0.96      0.96      2053
               U2R       0.94      0.68      0.79        44

          accuracy                           0.98     15780
         macro avg       0.97      0.93      0.95     15780
      weighted avg       0.98      0.98      0.98     15780



In [227]:
Xgb_Multi_CM_train = metrics.confusion_matrix(train_Y,xgb_predict)
Xgb_Multi_CM_train

array([[4966,    0,    8,   24,    1,    0],
       [   0,  201,    0,    0,    0,    0],
       [   9,    0, 6690,   21,   76,    0],
       [  32,    0,   13, 1637,    5,    0],
       [   2,    0,   51,   36, 1962,    2],
       [   0,    0,   12,    0,    2,   30]])

In [228]:
xgb_model_test = xgb_estimator.fit(test_x,test_y)
xgb_predict_test = xgb_model_test.predict(test_x)

[02:02:08] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { reg_alpa, scale_pos_weight, verbose } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




In [229]:
XGB_Multi_CM_Test = metrics.confusion_matrix(test_y,xgb_predict_test)
XGB_Multi_CM_Test

array([[2157,    0,    7,    2,    2,    0],
       [   0,   92,    0,    0,    0,    0],
       [   1,    0, 2889,    6,   19,    0],
       [  14,    0,    4,  711,    5,    0],
       [   0,    0,   17,   11,  804,    0],
       [   0,    0,    1,    0,    6,   16]])

In [230]:
print("KNN_Train","\n",KNN_MULTI_CM_Train)
print("DT_Train","\n",DT_MULTI_CM_Train)
print("Bagging_Train","\n",Bagging_MULTI_CM_Train)
print("RF_Train","\n",RF_MULTI_CM_Train)
print("ADA_Train","\n",ADA_MULTI_CM_Train)
print("GBM_Train","\n",GBM_Multi_CM_train)
print("Xgb_Train","\n",Xgb_Multi_CM_train)

print("KNN_Test","\n",KNN_MULTI_CM_Test)
print("DT_Test","\n",DT_MULTI_CM_Test)
print("Bagging_Test","\n",Bagging_MULTI_CM_Test)
print("RF_Test","\n",RF_MULTI_CM_Test)
print("ADA_Test","\n",ADA_MULTI_CM_Test)
print("GBM_Test","\n",GBM_Multi_CM_test)
print("Xgb_Test","\n",XGB_Multi_CM_Test)

KNN_Train 
 [[4987    0    0   12    0    0]
 [   0  201    0    0    0    0]
 [   1    0 6757    0   38    0]
 [  29    0    0 1646   12    0]
 [   0    0   33   19 2001    0]
 [   0    0    0    0    0   44]]
DT_Train 
 [[4819    0    7   19  154    0]
 [   0  201    0    0    0    0]
 [  67   63 6054  132  480    0]
 [  13    0   13 1075  586    0]
 [   5    5  134   19 1890    0]
 [   0    0    3    0   41    0]]
Bagging_Train 
 [[4986    0    0   13    0    0]
 [   0  201    0    0    0    0]
 [   1    0 6746    0   49    0]
 [  28    0    0 1647   12    0]
 [   0    0   22   19 2012    0]
 [   0    0    0    0    0   44]]
RF_Train 
 [[4959    0   12   20    8    0]
 [   0  201    0    0    0    0]
 [  33    0 6629   59   75    0]
 [  66    0   15 1606    0    0]
 [   0    0  174   89 1790    0]
 [   0    0   32    0    9    3]]
ADA_Train 
 [[   0    0 3394    0 1605    0]
 [   0  201    0    0    0    0]
 [  14    0 6655    0  127    0]
 [   0    0  377    0 1310    0]
 [   0    

In [ ]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(train_X, train_Y) 
gnb_predictions = gnb.predict(train_X) 
  
print(metrics.classification_report(train_Y,gnb_predictions))


In [ ]:
cm = metrics.confusion_matrix(test_y, gnb_predictions)
print(cm)

In [ ]:
svm_model = SVC(kernel = "linear",C=1).fit(train_X,train_Y)
svm_prediction_test = svm_model.predict(train_X)

In [ ]:
accuracy_test = svm_model.score(test_X,test_y)
accuracy_test

In [ ]:
svm_cm = metrics.classification_report(test_y,svm_prediction)

In [ ]:
print(svm_cm)